name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

# name: Terraform Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       # 🔹 Step 1: Checkout code (VERY IMPORTANT)
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # 🔹 Step 2: Setup Terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       # 🔹 Step 3: Configure AWS credentials
#       - name: Configure AWS Credentials
#         run: |
#           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws configure set region us-east-1

#       # 🔹 Step 4: Terraform Init (IMPORTANT PATH FIX)
#       - name: Terraform Init
#         working-directory: ./terraform
#         run: terraform init

#       # 🔹 Step 5: Terraform Plan
#       - name: Terraform Plan
#         working-directory: ./terraform
#         run: terraform plan

#       # 🔹 Step 6: Terraform Apply
#       - name: Terraform Apply
#         working-directory: ./terraform
#         run: terraform apply -auto-approve